name: Android Build #name of the workflow

on: pull_request   #defines when should this workflow be triggered

jobs: #we need to define the set of tasks that need to be run when the workflow starts
  build:
    runs-on: ubuntu-latest

    #first we need to checkout the code
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK # second setup jdk env that will be used
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests  # third run tests
        run: ./gradlew test

      - name: Build Project #build project
        run: ./gradlew assemble
